import { SpawnEntry } from '../types/spawn';

function make(
  no: string,
  pokemon: string,
  entry: string,
  bucket: string,
  weight: string,
  lvMin: string,
  lvMax: string,
  biomes: string,
  excludedBiomes: string,
  time: string,
  weather: string,
  context: string,
): SpawnEntry {
  const parsedBiomes = biomes
    ? biomes.split(',').map(b => b.trim()).filter(Boolean)
    : [];
  const parsedExcluded = excludedBiomes
    ? excludedBiomes.split(',').map(b => b.trim()).filter(Boolean)
    : [];

  const raw: Record<string, string> = {
    'No.': no, 'Pokémon': pokemon, 'Entry': entry, 'Bucket': bucket,
    'Weight': weight, 'Lv. Min': lvMin, 'Lv. Max': lvMax,
    'Biomes': biomes, 'Excluded Biomes': excludedBiomes,
    'Time': time, 'Weather': weather, 'Context': context,
    'Multipliers': '', 'Presets': 'Natural', 'Conditions': '',
    'Anticonditions': '', 'skyLightMin': '', 'skyLightMax': '',
    'canSeeSky': '', 'Patternkey=Value': '',
  };

  return {
    no, pokemon, entry, bucket: bucket.toLowerCase(), weight,
    lvMin, lvMax,
    biomes: parsedBiomes,
    excludedBiomes: parsedExcluded,
    time, weather,
    multipliers: '',
    context,
    presets: 'Natural',
    conditions: '',
    anticonditions: '',
    skyLightMin: '',
    skyLightMax: '',
    canSeeSky: '',
    patternKeyValue: '',
    biomesRaw: biomes,
    _raw: raw,
  };
}

export const SAMPLE_DATA: SpawnEntry[] = [
  make('0001','Bulbasaur',   '1','ultra-rare','6', '5','32','Jungle, Tropical Island',   '',           'any',  'any',  'grounded'),
  make('0004','Charmander',  '1','ultra-rare','6', '5','32','Savanna, Badlands',         '',           'any',  'any',  'grounded'),
  make('0007','Squirtle',    '1','ultra-rare','6', '5','32','Beach, River',              '',           'any',  'any',  'grounded'),
  make('0010','Caterpie',    '1','common',    '18','1','16','Forest, Jungle',            '',           'any',  'any',  'grounded'),
  make('0013','Weedle',      '1','common',    '18','1','16','Forest, Plains',            '',           'any',  'any',  'grounded'),
  make('0016','Pidgey',      '1','common',    '15','1','20','Plains, Savanna',           '',           'any',  'any',  'grounded'),
  make('0019','Rattata',     '1','common',    '20','1','20','Plains, Villages',          '',           'any',  'any',  'grounded'),
  make('0023','Ekans',       '1','uncommon',  '10','5','25','Desert, Badlands',          '',           'any',  'any',  'grounded'),
  make('0025','Pikachu',     '1','rare',      '8', '5','30','Forest, Jungle',            '',           'any',  'any',  'grounded'),
  make('0027','Sandshrew',   '1','uncommon',  '12','5','25','Desert, Badlands, Savanna', '',           'any',  'any',  'grounded'),
  make('0035','Clefairy',    '1','rare',      '5','10','30','Meadow, Snowy Plains',      'Forest',     'night','any',  'grounded'),
  make('0039','Jigglypuff',  '1','uncommon',  '10','5','25','Meadow, Plains',            '',           'any',  'any',  'grounded'),
  make('0043','Oddish',      '1','common',    '15','1','20','Forest, Jungle, Meadow',    '',           'night','any',  'grounded'),
  make('0050','Diglett',     '1','common',    '18','1','20','Desert, Badlands, Plains',  '',           'any',  'any',  'grounded'),
  make('0052','Meowth',      '1','uncommon',  '12','5','25','Villages, Plains',          '',           'any',  'any',  'grounded'),
  make('0054','Psyduck',     '1','uncommon',  '12','5','25','River, Lake, Beach',        '',           'any',  'any',  'grounded'),
  make('0058','Growlithe',   '1','rare',      '8', '5','30','Savanna, Plains',           '',           'any',  'any',  'grounded'),
  make('0060','Poliwag',     '1','common',    '15','1','20','River, Lake, Swamp',        '',           'any',  'any',  'grounded'),
  make('0063','Abra',        '1','rare',      '8', '5','30','Plains, Psychic Grove',     '',           'any',  'any',  'grounded'),
  make('0066','Machop',      '1','uncommon',  '12','5','25','Mountains, Hills',          '',           'any',  'any',  'grounded'),
  make('0074','Geodude',     '1','common',    '18','1','20','Mountains, Hills, Caves',   '',           'any',  'any',  'grounded'),
  make('0079','Slowpoke',    '1','uncommon',  '12','5','25','Beach, River, Lake',        '',           'any',  'any',  'grounded'),
  make('0081','Magnemite',   '1','uncommon',  '12','5','25','Plains',                    '',           'any',  'any',  'grounded'),
  make('0084','Doduo',       '1','common',    '15','1','20','Plains, Savanna',           '',           'any',  'any',  'grounded'),
  make('0086','Seel',        '1','uncommon',  '12','5','25','Frozen Ocean, Snowy Beach', '',           'any',  'any',  'grounded'),
  make('0088','Grimer',      '1','uncommon',  '12','5','25','Swamp, Mangrove Swamp',     '',           'any',  'any',  'grounded'),
  make('0092','Gastly',      '1','uncommon',  '12','5','25','Dark Forest, Haunted Biomes','',          'night','any',  'grounded'),
  make('0098','Krabby',      '1','common',    '15','1','20','Beach, River',              '',           'any',  'any',  'grounded'),
  make('0100','Voltorb',     '1','uncommon',  '12','5','25','Plains',                    '',           'any',  'any',  'grounded'),
  make('0102','Exeggcute',   '1','uncommon',  '12','5','25','Jungle, Tropical Island',   '',           'any',  'any',  'grounded'),
  make('0104','Cubone',      '1','uncommon',  '12','5','25','Desert, Badlands',          '',           'any',  'any',  'grounded'),
  make('0109','Koffing',     '1','uncommon',  '10','5','25','Swamp, Mangrove Swamp',     '',           'any',  'any',  'grounded'),
  make('0113','Chansey',     '1','ultra-rare','3','15','40','Meadow, Plains',            '',           'any',  'any',  'grounded'),
  make('0114','Tangela',     '1','rare',      '8', '5','30','Jungle, Meadow',            '',           'any',  'any',  'grounded'),
  make('0116','Horsea',      '1','common',    '15','1','20','Ocean, Beach',              '',           'any',  'any',  'grounded'),
  make('0118','Goldeen',     '1','common',    '18','1','20','River, Lake',               '',           'any',  'any',  'grounded'),
  make('0120','Staryu',      '1','uncommon',  '12','5','25','Beach, Ocean',              '',           'night','any',  'grounded'),
  make('0123','Scyther',     '1','rare',      '6','10','35','Jungle, Forest',            '',           'any',  'any',  'grounded'),
  make('0126','Magmar',      '1','rare',      '6','10','35','Nether Wastes, Basalt Deltas','',         'any',  'any',  'grounded'),
  make('0127','Pinsir',      '1','rare',      '6','10','35','Jungle, Forest',            '',           'any',  'any',  'grounded'),
  make('0129','Magikarp',    '1','common',    '25','1','15','River, Lake, Ocean',        '',           'any',  'any',  'grounded'),
  make('0131','Lapras',      '1','ultra-rare','3','15','40','Frozen Ocean, Snowy Beach', '',           'any',  'any',  'grounded'),
  make('0133','Eevee',       '1','rare',      '7','5', '30','Meadow, Plains, Villages',  '',           'any',  'any',  'grounded'),
  make('0137','Porygon',     '1','ultra-rare','3','15','40','Plains',                    '',           'any',  'any',  'grounded'),
  make('0138','Omanyte',     '1','ultra-rare','4','10','35','Beach, Ocean',              '',           'any',  'any',  'grounded'),
  make('0140','Kabuto',      '1','ultra-rare','4','10','35','Beach, Desert',             '',           'any',  'any',  'grounded'),
  make('0143','Snorlax',     '1','ultra-rare','2','20','50','Plains, Forest',            '',           'any',  'any',  'grounded'),
  make('0147','Dratini',     '1','ultra-rare','3','15','40','River, Lake',               '',           'any',  'any',  'grounded'),
  make('0152','Chikorita',   '1','ultra-rare','6', '5','32','Meadow, Forest',            '',           'any',  'any',  'grounded'),
  make('0155','Cyndaquil',   '1','ultra-rare','6', '5','32','Savanna, Plains',           '',           'any',  'any',  'grounded'),
  make('0158','Totodile',    '1','ultra-rare','6', '5','32','River, Swamp',              '',           'any',  'any',  'grounded'),
  make('0163','Hoothoot',    '1','common',    '15','1','20','Forest, Plains',            '',           'night','any',  'grounded'),
  make('0165','Ledyba',      '1','common',    '18','1','16','Meadow, Forest',            '',           'any',  'any',  'grounded'),
  make('0170','Chinchou',    '1','uncommon',  '12','5','25','Deep Ocean, Ocean',         '',           'any',  'any',  'grounded'),
  make('0175','Togepi',      '1','ultra-rare','3','10','30','Meadow, Plains',            '',           'any',  'any',  'grounded'),
  make('0179','Mareep',      '1','uncommon',  '12','5','25','Plains, Meadow',            '',           'any',  'any',  'grounded'),
  make('0183','Marill',      '1','common',    '18','1','20','River, Lake, Swamp',        '',           'any',  'any',  'grounded'),
  make('0187','Hoppip',      '1','common',    '18','1','20','Meadow, Plains',            '',           'any',  'any',  'grounded'),
  make('0193','Yanma',       '1','uncommon',  '10','5','25','Swamp, Jungle',             '',           'any',  'any',  'grounded'),
  make('0194','Wooper',      '1','common',    '18','1','20','Swamp, River, Mangrove Swamp','',         'any',  'any',  'grounded'),
  make('0196','Espeon',      '1','rare',      '5','20','50','Meadow, Plains',            '',           'day',  'any',  'grounded'),
  make('0197','Umbreon',     '1','rare',      '5','20','50','Forest, Dark Forest',       '',           'night','any',  'grounded'),
  make('0200','Misdreavus',  '1','rare',      '6','10','35','Dark Forest, Haunted Biomes','',          'night','any',  'grounded'),
  make('0204','Pineco',      '1','uncommon',  '12','5','25','Forest, Birch Forest',      '',           'any',  'any',  'grounded'),
  make('0209','Snubbull',    '1','uncommon',  '12','5','25','Meadow, Plains, Villages',  '',           'any',  'any',  'grounded'),
  make('0213','Shuckle',     '1','rare',      '5','10','35','Mountains, Hills',          '',           'any',  'any',  'grounded'),
  make('0215','Sneasel',     '1','rare',      '7','10','35','Snowy Plains, Snowy Taiga', '',           'night','any',  'grounded'),
  make('0216','Teddiursa',   '1','uncommon',  '12','5','25','Forest, Taiga',             '',           'any',  'any',  'grounded'),
  make('0220','Swinub',      '1','common',    '18','1','20','Snowy Plains, Ice Spikes',  '',           'any',  'any',  'grounded'),
  make('0222','Corsola',     '1','rare',      '6','10','30','Warm Ocean, Beach',         '',           'any',  'any',  'grounded'),
  make('0225','Delibird',    '1','uncommon',  '10','5','25','Snowy Plains, Ice Spikes',  '',           'any',  'any',  'grounded'),
  make('0231','Phanpy',      '1','common',    '15','1','20','Plains, Savanna, Hills',    '',           'any',  'any',  'grounded'),
  make('0234','Stantler',    '1','uncommon',  '12','5','25','Forest, Taiga, Meadow',     '',           'any',  'any',  'grounded'),
  make('0246','Larvitar',    '1','ultra-rare','4','10','35','Mountains, Badlands',       '',           'any',  'any',  'grounded'),
  make('0252','Treecko',     '1','ultra-rare','6', '5','32','Jungle, Forest',            '',           'any',  'any',  'grounded'),
  make('0255','Torchic',     '1','ultra-rare','6', '5','32','Savanna, Plains',           '',           'any',  'any',  'grounded'),
  make('0258','Mudkip',      '1','ultra-rare','6', '5','32','Swamp, River',              '',           'any',  'any',  'grounded'),
  make('0263','Zigzagoon',   '1','common',    '20','1','20','Forest, Plains, Meadow',    '',           'any',  'any',  'grounded'),
  make('0270','Lotad',       '1','common',    '18','1','20','Swamp, Lake, Meadow',       '',           'any',  'any',  'grounded'),
  make('0273','Seedot',      '1','common',    '18','1','20','Forest, Jungle',            '',           'any',  'any',  'grounded'),
  make('0278','Wingull',     '1','common',    '15','1','20','Beach, Ocean',              '',           'any',  'any',  'grounded'),
  make('0280','Ralts',       '1','rare',      '7', '5','30','Meadow, Plains',            '',           'any',  'any',  'grounded'),
  make('0285','Shroomish',   '1','common',    '18','1','20','Forest, Mushroom Fields',   '',           'any',  'any',  'grounded'),
  make('0287','Slakoth',     '1','uncommon',  '12','5','25','Jungle, Forest',            '',           'any',  'any',  'grounded'),
  make('0290','Nincada',     '1','rare',      '8', '5','30','Forest, Plains',            '',           'any',  'any',  'grounded'),
  make('0298','Azurill',     '1','uncommon',  '12','1','20','River, Lake, Swamp',        '',           'any',  'any',  'grounded'),
  make('0300','Skitty',      '1','uncommon',  '12','5','25','Meadow, Plains',            '',           'any',  'any',  'grounded'),
  make('0302','Sableye',     '1','rare',      '6','10','35','Caves, Dark Forest',        '',           'any',  'any',  'grounded'),
  make('0304','Aron',        '1','uncommon',  '12','5','25','Mountains, Hills, Caves',   '',           'any',  'any',  'grounded'),
  make('0307','Meditite',    '1','uncommon',  '12','5','25','Mountains, Jungle',         '',           'any',  'any',  'grounded'),
  make('0309','Electrike',   '1','uncommon',  '12','5','25','Plains, Savanna',           '',           'any',  'thunderstorm','grounded'),
  make('0318','Carvanha',    '1','uncommon',  '12','5','25','River, Jungle',             '',           'any',  'any',  'grounded'),
  make('0322','Numel',       '1','uncommon',  '12','5','25','Savanna, Badlands',         '',           'any',  'any',  'grounded'),
  make('0325','Spoink',      '1','uncommon',  '12','5','25','Mountains, Hills',          '',           'any',  'any',  'grounded'),
  make('0333','Swablu',      '1','uncommon',  '12','5','25','Meadow, Plains, Mountains', '',           'any',  'any',  'grounded'),
  make('0336','Seviper',     '1','rare',      '6','10','35','Jungle, Savanna',           '',           'any',  'any',  'grounded'),
  make('0339','Barboach',    '1','common',    '18','1','20','River, Lake, Swamp',        '',           'any',  'any',  'grounded'),
  make('0341','Corphish',    '1','common',    '15','1','20','River, Lake',               '',           'any',  'any',  'grounded'),
  make('0349','Feebas',      '1','ultra-rare','2','1', '20','River, Lake',               '',           'any',  'any',  'grounded'),
  make('0351','Castform',    '1','rare',      '5','15','40','Plains, Meadow',            '',           'any',  'any',  'grounded'),
  make('0353','Shuppet',     '1','uncommon',  '12','5','25','Dark Forest, Haunted Biomes','',          'night','any',  'grounded'),
  make('0357','Tropius',     '1','rare',      '6','10','35','Jungle, Tropical Island',   '',           'any',  'any',  'grounded'),
  make('0361','Snorunt',     '1','uncommon',  '12','5','25','Snowy Plains, Ice Spikes',  '',           'any',  'any',  'grounded'),
  make('0363','Spheal',      '1','uncommon',  '12','5','25','Frozen Ocean, Snowy Beach', '',           'any',  'any',  'grounded'),
  make('0370','Luvdisc',     '1','uncommon',  '12','5','25','Warm Ocean, Beach',         '',           'any',  'any',  'grounded'),
  make('0374','Beldum',      '1','ultra-rare','3','15','40','Mountains, Plains',         '',           'any',  'any',  'grounded'),
];
